# Generated by Django 5.0.11 on 2025-01-22 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_pregunta', models.CharField(max_length=30, unique=True)),
                ('Opcion_A', models.CharField(max_length=30)),
                ('Opcion_B', models.CharField(max_length=30)),
                ('Opcion_C', models.CharField(max_length=30)),
                ('Opcion_D', models.CharField(max_length=30)),
                ('Respuesta_Corecta', models.CharField(max_length=30)),
                ('Puntos', models.IntegerField(default=0)),
                ('Id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jugador.usuario')),
            ],
        ),
    ]
