# Generated by Django 5.0.11 on 2025-01-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_alter_preguntas_nombre_pregunta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preguntas',
            new_name='Pregunta',
        ),
    ]
